// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef macierzUI_h
#define macierzUI_h
#include <FL/Fl.H>
#include "macierze.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Slider.H>

class macierzUI : public Fl_Group {
public:
  unsigned numer;
  macierzUI(int x, int y, int w, int h, const char *label = 0) ;
  Fl_Value_Input *a;
private:
  inline void cb_a_i(Fl_Value_Input*, void*);
  static void cb_a(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *b;
private:
  inline void cb_b_i(Fl_Value_Input*, void*);
  static void cb_b(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *c;
private:
  inline void cb_c_i(Fl_Value_Input*, void*);
  static void cb_c(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *d;
private:
  inline void cb_d_i(Fl_Value_Input*, void*);
  static void cb_d(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *e;
private:
  inline void cb_e_i(Fl_Value_Input*, void*);
  static void cb_e(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *f;
private:
  inline void cb_f_i(Fl_Value_Input*, void*);
  static void cb_f(Fl_Value_Input*, void*);
public:
  Fl_Slider *P;
private:
  inline void cb_P_i(Fl_Slider*, void*);
  static void cb_P(Fl_Slider*, void*);
  static unsigned ostatni;
public:
  void Resetuj();
  void Ustaw(const Macierz &M);
};
#endif
