// generated by Fast Light User Interface Designer (fluid) version 1.0105

#ifndef przekUI_h
#define przekUI_h
#include <FL/Fl.H>
#include <cmath>
#include <cerrno>
#include <cmath>
#include "macierze.h"
#include "app.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>

class przekUI : public Fl_Group {
public:
  unsigned numer;
  przekUI(int x, int y, int w, int h, const char *label = 0) ;
  Fl_Slider *P;
private:
  inline void cb_P_i(Fl_Slider*, void*);
  static void cb_P(Fl_Slider*, void*);
public:
  Fl_Value_Input *c;
private:
  inline void cb_c_i(Fl_Value_Input*, void*);
  static void cb_c(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *f;
private:
  inline void cb_f_i(Fl_Value_Input*, void*);
  static void cb_f(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *theta;
private:
  inline void cb_theta_i(Fl_Value_Input*, void*);
  static void cb_theta(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *fi;
private:
  inline void cb_fi_i(Fl_Value_Input*, void*);
  static void cb_fi(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *r;
private:
  inline void cb_r_i(Fl_Value_Input*, void*);
  static void cb_r(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *s;
private:
  inline void cb_s_i(Fl_Value_Input*, void*);
  static void cb_s(Fl_Value_Input*, void*);
  static unsigned ostatni;
public:
  void Resetuj();
  void Ustaw(const Macierz &M);
};
#endif
